set -g default-terminal "tmux-256color"

# set -g prefix C-a
# unbind C-b
# bind-key C-a send-prefix

# unbind %
# bind | split-window -h

# unbind '"'
# bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

#list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-resurrect' #presist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' #automatically saves sessions for you every 15 minutes

set -g @plugin 'wfxr/tmux-power'
set -g @tmux_power_theme 'moon'
# set -g @tmux_power_left_a '#{b:pane_current_path}'
set -g @tmux_power_left_a '#S'

set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

set -g @plugin 'sainnhe/tmux-fzf'
set -g @tmux-fzf-launch-key 'C-f'
set -g @tmux_fzf_options "-p -w 62% -h 38% -m"

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'laktak/extrakto'
set -g @extrakto_copy_key 'tab'      # کلید کپی به کلیپ‌بورد
set -g @extrakto_insert_key 'enter'  # کلید insert به pane
set -g @extrakto_default_filter 'path'  # فیلتر پیش‌فرض هنگام باز شدن

set -g @tmux_power_right_w 'CPU #{cpu_percentage}'
set -g @tmux_power_right_x 'BAT #{battery_percentage}'


# set -g @themepack 'powerline/default/cyan'

set -g @tmux_power_right_arrow_icon ''
set -g @tmux_power_left_arrow_icon ''
set -g @tmux_power_date_icon ''
set -g @tmux_power_time_icon ''
set -g @tmux_power_user_icon ''
set -g @tmux_power_session_icon ''

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

set -g allow-passthrough on
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
